apiVersion: v1
kind: Service
metadata:
  name: devopsexamapp-service
  namespace: devopsexamapp
spec:
  type: LoadBalancer
  selector:
    app: devopsexamapp
  ports:
    - port: 80
      targetPort: 3000